#:schema base
# The schema line above is for taplo to validate this file since a `zola`
# schema is not available.

# Vyolet config file.

# Important: this file is only used when developing the theme. It is not used
# when the theme is used as a dependency in a site. To modify the settings for
# your site, use the `config.toml` file in the root of your site, using this
# file as a reference.

base_url         = "."
compile_sass     = true
default_language = "en"
feed_limit       = 20
hard_link_static = false
ignored_content  = ["static/**/*.inkscape.svg"]

# Site specific.

# The site theme to use.
# theme = "vyolet"

# Output directory, /public by default.
output_dir = "public"

# Minify the generated HTML files for prod.
minify_html = true

# Don't build a search index since this feature is not used.
build_search_index = false


[markdown]
# Configuration of the Markdown rendering.
external_links_no_follow    = true
external_links_no_referrer  = true
external_links_target_blank = true
extra_syntaxes_and_themes   = []
highlight_code              = true
highlight_theme             = "base16-ocean-dark"
render_emoji                = false
smart_punctuation           = false


[link_checker]
# Configuration of the link checker.
external_level       = "error"
internal_level       = "error"
skip_anchor_prefixes = ["https://caniuse.com/"]
skip_prefixes        = ["http://[2001:db8::]/"]


[slugify]
# Slugification strategies.
anchors    = "on"
paths      = "on"
taxonomies = "on"


# Theme variables.
[extra]
header_menu = [{ url = "pricing" }, { url = "solution" }, { url = "blog" }]

header_languages = [
	# English first.
	{ lang = "en", name = "English" },
	# cspell:disable
	{ lang = "de", name = "Deutsch" },
	{ lang = "es", name = "Español" },
	{ lang = "fr", name = "Français" },
	{ lang = "it", name = "Italiano" },
	{ lang = "nl", name = "Nederlands" },
	{ lang = "pt", name = "Português" },
	# cspell:enable
]

error_404 = [
	# English is already in 404.html.
	# cspell:disable
	{ lang = "de", title = "Seite nicht gefunden", text = "Die angeforderte Seite existiert nicht oder wurde an eine andere Adresse verschoben." },
	{ lang = "es", title = "Página no encontrada", text = "La página solicitada no existe o se ha movido a otra dirección." },
	{ lang = "fr", title = "Page introuvable", text = "La page demandée n'existe pas ou a été déplacée à une autre adresse." },
	{ lang = "it", title = "Pagina non trovata", text = "La pagina richiesta non esiste o è stata spostata a un altro indirizzo." },
	{ lang = "nl", title = "Pagina niet gevonden", text = "De gevraagde pagina bestaat niet of is verplaatst naar een ander adres." },
	{ lang = "pt", title = "Página não encontrada", text = "A página solicitada não existe ou foi movida para outro endereço." },
	# cspell:enable
]

header_buttons = [
	{ url = "login", name = "Log in", state = "disabled" },
	{ url = "signup", name = "Sign up", state = "disabled" },
]

# Social links.
social_header = "Follow us"
github        = "ystorian/vyolet"
linkedin      = "in/flavienscheurer"
mailto        = "contact@example.com"
mastodon      = "https://infosec.exchange"
twitter       = "."


navbar_links = [
	{ name = "about", url = "/about" },
	{ name = "archive", url = "/archive" },
	{ name = "tags", url = "/tags" },
	{ name = "categories", url = "/categories" },
	{ name = "links", url = "/links" },
]

# Footer.
status = "https://uptimerobot.com/?rid=98b9cf6cfd8c4b"

footer_links = [
	{ name = "about", url = "/about" },
	{ name = "archive", url = "/archive" },
	{ name = "tags", url = "/tags" },
	{ name = "categories", url = "/categories" },
	{ name = "links", url = "/links" },
]

# Analytics.
plausible = "ystorian.com"


# Multilingual support.
[languages]

# Default values (English).
[languages.en]
title              = "Vyolet"
description        = "Ystorian theme"
generate_feed      = true
feed_filename      = "atom.xml"
build_search_index = false
search             = { include_title = false, include_description = false, include_path = true, include_content = true }

taxonomies = [
	{ name = "categories", paginate_by = 3 },
	{ name = "tags", paginate_by = 3, rss = true },
]

[languages.en.translations]
language_name = "English"
about         = "About"
blog          = "Blog"
follow_us     = "Follow us"
home          = "Home"
links         = "Links"
login         = "Log in"
pricing       = "Pricing"
privacy       = "Privacy"
security      = "Security"
solution      = "Solutions"


# Additional languages definition.
# cspell:disable

# French.
[languages.fr]
title       = "Vyolet"
description = "Thème Ystorian"

[languages.fr.translations]
language_name = "Français"
about         = "A propos"
blog          = "Blog"
follow_us     = "Suivez-nous"
home          = "Accueil"
login         = "Connexion"
pricing       = "Tarifs"
privacy       = "Confidentialité"
security      = "Sécurité"
solution      = "Solutions"
