#:schema base
# The schema line above is for taplo to validate this file since a `zola`
# schema is not available.

# Vyolet config file.

# Important: this file is only used when developing the theme. It is not used
# when the theme is used as a dependency in a site. To modify the settings for
# your site, use the `config.toml` file in the root of your site, using this
# file as a reference.

base_url         = "."
compile_sass     = true
default_language = "en"
feed_limit       = 20
hard_link_static = false
ignored_content  = ["static/**/*.inkscape.svg"]

# Site specific.

# The site theme to use.
# theme = "vyolet"

# Output directory, /public by default.
output_dir = "public"

# Minify the generated HTML files for prod.
minify_html = true

# Don't build a search index since this feature is not used.
build_search_index = false


[markdown]
# Configuration of the Markdown rendering.
external_links_no_follow    = true
external_links_no_referrer  = true
external_links_target_blank = true
extra_syntaxes_and_themes   = []
highlight_code              = true
highlight_theme             = "base16-ocean-dark"
render_emoji                = false
smart_punctuation           = false


[link_checker]
# Configuration of the link checker.
external_level       = "error"
internal_level       = "error"
skip_anchor_prefixes = ["https://caniuse.com/"]
skip_prefixes        = ["http://[2001:db8::]/"]


[slugify]
# Slugification strategies.
anchors    = "on"
paths      = "on"
taxonomies = "on"


# Theme variables.
[extra]
# Theme version.
version = "0.1.0"
# OpenGraph.
# Image must be at least 1200x630.
og_image = "vyolet-opengraph-1200x630.png"
# Analytics.
plausible = "ystorian.com/vyolet"

# Header.
navbar_menu = [
	{ key = "pricing", url = "pricing" },
	{ key = "solution", url = "solution" },
	{ key = "blog", url = "blog" },
]

navbar_buttons = [
	{ key = "login", url = "login", primary = true, disabled = true },
]

# Footer.
# Left column.
left_column_label = "news"
left_column = [
	{ key = "blog", url = "blog" },
	{ key = "newsletter", url = "newsletter" },
]
# Social links.
github   = "ystorian/vyolet"
linkedin = "company/Ystorian"
mailto   = "contact@ystorian.com"
mastodon = "https://infosec.exchange/@ystorian"
# Middle column.
middle_column_label = "products"
middle_column = [
	{ key = "solution", url = "@solution" },
	{ key = "documentation", url = "@documentation" },
	{ key = "pricing", url = "@pricing" },
	{ key = "status", url = "https://uptimerobot.com/?rid=98b9cf6cfd8c4b" },
]
# Right column.
right_column_label = "company"
right_column = [
	{ key = "about", url = "about" },
	{ key = "contact", url = "contact" },
	{ key = "privacy", url = "privacy" },
	{ key = "security", url = "security" },
	{ key = "legal", url = "contact" },
]


# Multilingual support.

# List of languages to display in the header.
# The theme cannot use the [languages] section because it is not available on
# all pages.
# This will be refactored in the future, when Zola will have proper multilingual
# support, possibly with version 2.0.
header_languages = [
	# English first.
	{ lang = "en", name = "English" },
	# cspell:disable
	{ lang = "de", name = "Deutsch" },
	{ lang = "es", name = "Español" },
	{ lang = "fr", name = "Français" },
	{ lang = "it", name = "Italiano" },
	{ lang = "nl", name = "Nederlands" },
	{ lang = "pt", name = "Português" },
	{ lang = "rm", name = "Rumantsch" },
	# cspell:enable
]

# Translations for the 404 page.
# Note: English is already in 404.html.
error_404 = [
	# cspell:disable
	{ lang = "de", title = "Seite nicht gefunden", text = "Die angeforderte Seite existiert nicht oder wurde an eine andere Adresse verschoben." },
	{ lang = "es", title = "Página no encontrada", text = "La página solicitada no existe o se ha movido a otra dirección." },
	{ lang = "fr", title = "Page introuvable", text = "La page demandée n'existe pas ou a été déplacée à une autre adresse." },
	{ lang = "it", title = "Pagina non trovata", text = "La pagina richiesta non esiste o è stata spostata a un altro indirizzo." },
	{ lang = "nl", title = "Pagina niet gevonden", text = "De gevraagde pagina bestaat niet of is verplaatst naar een ander adres." },
	{ lang = "pt", title = "Página não encontrada", text = "A página solicitada não existe ou foi movida para outro endereço." },
	{ lang = "rm", title = "Betg chattà la pagina", text = "La pagina dumandada n’exista betg u è vegnida spustada ad in’autra adressa." },
	# cspell:enable
]

[languages]

# Default values (English).
[languages.en]
title              = "Vyolet"
description        = "Ystorian theme"
generate_feed      = true
feed_filename      = "atom.xml"
build_search_index = false
search             = { include_title = false, include_description = false, include_path = true, include_content = true }

taxonomies = [
	{ name = "categories", paginate_by = 3 },
	{ name = "tags", paginate_by = 3, rss = true },
]

[languages.en.translations]
language_name = "English"
about         = "About"
blog          = "Blog"
company       = "Company"
contact       = "Contact"
documentation = "Documentation"
follow_us     = "Follow us"
home          = "Home"
login         = "Log in"
made          = "Made with 💜"
news          = "News"
newsletter    = "Newsletter"
pricing       = "Pricing"
privacy       = "Privacy"
products      = "Products"
security      = "Security"
solution      = "Solutions"
status        = "System status"
translated    = "This page has been automatically translated and may contain translation errors"


# Additional languages definition.
# cspell:disable

# French.
[languages.fr]
title       = "Vyolet"
description = "Thème Ystorian"

[languages.fr.translations]
language_name = "Français"
about         = "A propos"
blog          = "Blog"
company       = "Entreprise"
contact       = "Contact"
documentation = "Documentation"
follow_us     = "Suivez-nous"
home          = "Accueil"
login         = "Connexion"
made          = "Fait avec 💜"
news          = "Actualités"
newsletter    = "Newsletter"
pricing       = "Tarifs"
privacy       = "Confidentialité"
products      = "Produits"
security      = "Sécurité"
solution      = "Solutions"
status        = "État du système"
translated    = "Cette page a été traduite automatiquement et peut contenir des erreurs de traduction"


# German.
[languages.de]
title       = "Vyolet"
description = "Ystorian-Theme"

[languages.de.translations]
language_name = "Deutsch"
about         = "Über uns"
blog          = "Blog"
company       = "Unternehmen"
contact       = "Kontakt"
documentation = "Dokumentation"
follow_us     = "Folgen Sie uns"
home          = "Startseite"
login         = "Anmeldung"
made          = "Hergestellt mit 💜"
news          = "Neuigkeiten"
newsletter    = "Newsletter"
pricing       = "Preise"
privacy       = "Datenschutz"
products      = "Produkte"
security      = "Sicherheit"
solution      = "Lösungen"
status        = "Systemstatus"
translated    = "Diese Seite wurde maschinell übersetzt und kann Übersetzungsfehler enthalten"


# Italian.
[languages.it]
title       = "Vyolet"
description = "Tema Ystorian"

[languages.it.translations]
language_name = "Italiano"
about         = "Informazioni"
blog          = "Blog"
company       = "Azienda"
contact       = "Contatti"
documentation = "Documentazione"
follow_us     = "Seguici"
home          = "Home"
login         = "Accedi"
made          = "Fatto con 💜"
news          = "Novità"
newsletter    = "Newsletter"
pricing       = "Prezzi"
privacy       = "Privacy"
products      = "Prodotti"
security      = "Sicurezza"
solution      = "Soluzioni"
status        = "Stato del sistema"
translated    = "Questa pagina è stata tradotta automaticamente e può contenere errori di traduzione"


# Spanish.
[languages.es]
title       = "Vyolet"
description = "Tema Ystorian"

[languages.es.translations]
language_name = "Español"
about         = "Acerca de"
blog          = "Blog"
company       = "Empresa"
contact       = "Contacto"
documentation = "Documentación"
follow_us     = "Síguenos"
home          = "Inicio"
login         = "Iniciar sesión"
made          = "Hecho con 💜"
news          = "Noticias"
newsletter    = "Boletín"
pricing       = "Precios"
privacy       = "Privacidad"
products      = "Productos"
security      = "Seguridad"
solution      = "Soluciones"
status        = "Estado del sistema"
translated    = "Esta página ha sido traducida automáticamente y puede contener errores de traducción"


# Portuguese.
[languages.pt]
title       = "Vyolet"
description = "Tema Ystorian"

[languages.pt.translations]
language_name = "Português"
about         = "Sobre"
blog          = "Blog"
company       = "Empresa"
contact       = "Contato"
documentation = "Documentação"
follow_us     = "Siga-nos"
home          = "Início"
login         = "Entrar"
made          = "Feito com 💜"
news          = "Notícias"
newsletter    = "Newsletter"
pricing       = "Preços"
privacy       = "Privacidade"
products      = "Produtos"
security      = "Segurança"
solution      = "Soluções"
status        = "Estado do sistema"
translated    = "Esta página foi automaticamente traduzida e pode conter erros de tradução"


# Dutch.
[languages.nl]
title       = "Vyolet"
description = "Ystorian-thema"

[languages.nl.translations]
language_name = "Nederlands"
about         = "Over"
blog          = "Blog"
company       = "Bedrijf"
contact       = "Contact"
documentation = "Documentatie"
follow_us     = "Volg ons"
home          = "Home"
login         = "Inloggen"
made          = "Gemaakt met 💜"
news          = "Nieuws"
newsletter    = "Nieuwsbrief"
pricing       = "Prijzen"
privacy       = "Privacy"
products      = "Producten"
security      = "Veiligheid"
solution      = "Oplossingen"
status        = "Systeemstatus"
translated    = "Deze pagina is automatisch vertaald en kan vertaalfouten bevatten"


# Romansh.
[languages.rm]
title       = "Vyolet"
description = "Tema d'Ystorian"

[languages.rm.translations]
# Sources:
# - https://www.dicziunari.ch/rm/
# - https://try.rumants.ch/
language_name = "Rumantsch"
about         = "Sur"
blog          = "Blog"
company       = "Interpresa"
contact       = "Contact"
documentation = "Documentaziun"
follow_us     = "Suandai a nus"
home          = "Pagina iniziala"
login         = "Connexiun"
made          = "Fatg cun 💜"
news          = "Novitads"
newsletter    = "Newsletter"
pricing       = "Pretschs"
privacy       = "Protecziun da datas"
products      = "Products"
security      = "Segirtad"
solution      = "Soluziuns"
status        = "Status da sistem"
translated    = "Questa pagina è vegnida translatada automaticamain e po cuntegnair sbagls da translaziun"
