name               = "Vyolet"
description        = "Ystorian theme"
homepage           = "https://github.com/Ystorian/vyolet"
min_version        = "0.16.0"
compile_sass       = true
base_url           = "."
build_search_index = false
generate_feed      = true

taxonomies = [
	{ name = "categories", paginate_by = 3 },
	{ name = "tags", paginate_by = 3, rss = true },
]

[extra]
# site_title            = "Ystorian"
# site_description      = "Real-time security inventory"
# theme_color           = "hsl(265, 100%, 60%)"
# theme_color_rgb       = "#8533ff"
# plausible_data_domain = ""
