#:schema zola
# The schema line above is to prevent taplo to validate this file.
# Taplo is used by the Even Better TOML extension in VS Code,
# Since the `zola` schema does not exist, this disables taplo for this file.

name        = "Vyolet"
description = "Ystorian theme"
homepage    = "https://github.com/Ystorian/vyolet"
min_version = "0.16.0"
demo        = "https://ystorian.com"

[author]
name     = "Flavien Scheurer"
homepage = "https://github.com/cyann/"

[extra]
theme_color     = "hsl(265, 100%, 60%)"
theme_color_rgb = "#8533ff"

twitter  = "ystorian"
linkedin = "Ystorian"
github   = "Ystorian"
mailto   = "contact@ystorian.com"
# plausible_data_domain = "ystorian.com"
